server:
  port: 8181
  
spring:  application:    name: API-GATEWAY
  cloud:    gateway:      routes:      - id: BOOK-INVENTORY
        uri: lb://BOOK-INVENTORY
        predicates:        - Path=/bookiventory/**
        filters:
        - name: CircuitBreaker
          args:
            name: BOOK-INVENTORY
            fallbackuri: forward:/bookinventoryservicefallback
            
      - id: BOOK-LENDING
        uri: lb://BOOK-LENDING
        predicates:
        - Path=/booklending/**
        filters:
        - name: CircuitBreaker
          args:
            name: BOOK-LENDING
            fallbackuri: forward:/booklendingservicefallback

      - id: BOOK-PURCHASE
        uri: lb://BOOK-PURCHASE
        predicates:
        - Path=/bookpurchase/**
        filters:
        - name: CircuitBreaker
          args:
            name: BOOK-PURCHASE
            fallbackuri: forward:/bookpurchaseservicefallback

  hystrix:
   command:
     fallbackcmd:
       execution:
         isolation:
           thread:
             timeoutInMilliseconds: 4000


management:  endpoints:    web:      exposure:        include:        - hystrix.stream
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost