server:
  port: 8003

spring:
  application:
    name: BOOK-PURCHASE
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/book_purchase?useSSL=false
   username: vivek
   password: root
  jpa:
   #properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
   hibernate.ddl-auto: update
   generate-ddl: true
   show-sql: true
   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
